org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8

# Minecraft / Fabric versions
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
fabric_version=0.141.6+1.21.11

# Mod metadata
mod_version=1.0.0
maven_group=com.abdy2
archives_base_name=aotvpathfinder

# Java version
java_version=21
