org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / Fabric versions
minecraft_version=26.1.2
loader_version=0.19.3
fabric_version=0.155.2+26.1.2

# Mod metadata
mod_version=1.0.0
maven_group=com.abdy2
archives_base_name=aotvpathfinder

# Java version
java_version=25
